# Generated by Django 5.0.7 on 2024-08-23 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminclick', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminclick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=99999999)),
                ('profile_pic', models.ImageField(null=True, upload_to='picture/admin/admin.jpg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=99999999)),
                ('profile_pic', models.ImageField(default='picture/artist/hi.jpg', null=True, upload_to='picture/artist')),
                ('is_approved', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('mediums', models.ManyToManyField(blank=True, to='adminclick.mediumofwaste')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=99999999)),
                ('profile_pic', models.ImageField(default='picture/donor/hi.jpg', null=True, upload_to='picture/donor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
