# Generated by Django 5.0.7 on 2024-08-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_product_categories_alter_product_stock'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
