# Generated by Django 5.0.7 on 2024-09-03 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_product'),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='interest_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donors.interestrequest'),
        ),
    ]
